export type StageId =
  | "details"
  | "measurement"
  | "designing"
  | "booking"
  | "finalMeasurement"
  | "clientdocumentation"
  | "clientApproval"
  | "techcheck"
  | "orderLogin"
  | "production"
  | "readyToDispatch"
  | "siteReadiness"
  | "dispatchPlanning"
  | "dispatch"
  | "underInstallation"
  | "finalHandover";
